
## Make sure strings containing colors are in quotes.
Message Of The Day: "&3Loqua City &7\\& &bMinigames!"

## Format in a list style:
## Splashes:
##    - Splash 1
##    - Splash 2
##    - Splash 3
Splashes:
  - Splashy splash!