
## Make sure strings containing colors are in quotes.
Message Of The Day: "A Minecraft Server"

## Format in a list style:
## Splashes:
##    - Splash 1
##    - Splash 2
##    - Splash 3
Splashes: